export interface SubTask {
  id: string;
  title: string;
  completed: boolean;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  date: string; // YYYY-MM-DD
  time?: string; // HH:MM
  priority: 'baixa' | 'media' | 'alta';
  category: 'Trabalho' | 'Estudos' | 'Saúde' | 'Pessoal' | 'Outros';
  completed: boolean;
  reminderActive: boolean;
  reminderTime?: string; // HH:MM
  smartTip?: string; // Procrastination tip generated by Gemini
  subtasks: SubTask[];
}

export interface Goal {
  id: string;
  title: string;
  type: 'semanal' | 'longo_prazo';
  category: 'Redes Sociais' | 'Profissional' | 'Estudos' | 'Saúde' | 'Financeiro' | 'Outros';
  targetValue: number;
  currentValue: number;
  unit: string; // e.g. "vídeos", "seguidores", "horas"
  deadline?: string; // YYYY-MM-DD or descriptive (e.g. "4 meses")
  completed: boolean;
  startDate: string; // YYYY-MM-DD
}

export interface TaskTip {
  taskId: string;
  tip: string;
}

export interface AIRoutinesResponse {
  orderedTaskIds: string[];
  tips: TaskTip[];
  motivationQuote: string;
  procrastinationAnalysis: string;
}
